#! /bin/bash
bspc config border_width        2
bspc config window_gap          32
bspc config split_ratio         0.618

bspc monitor -d I II III IV

bspc rule -a Chromium desktop=^3
bspc rule -a Steam desktop=^2
bspc rule -a Feh floating=on
bspc rule -a Atom desktop=^1
bspc rule -a Allegro desktop=^2
